name: moises_dart
description: music.ai's Moises for Dart
version: 0.0.1
repository: https://github.com/melody-io/music.ai.dart

environment:
  sdk: ^3.3.0-152.0.dev

dependencies:
  path: ^1.8.0
  http: ^1.1.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
